api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "ext-cart-transform"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.transform.run"
  input_query = "cart_transform_run.graphql"
  export = "cart_transform_run"

  [extensions.build]
  command = "echo 'build the wasm'"
  path = ""
  watch = []

  [extensions.ui.paths]
  create = "/"
  details = "/"
