
api_version = "2025-04"
[[extensions]]
name = "t:name"
handle = "ext-product-configuration"
type = "ui_extension"


# Both extension points are required
[[extensions.targeting]]
module = "./src/ProductDetailsConfigurationExtension.tsx"
target = "admin.product-details.configuration.render"
[extensions.targeting.urls]
edit = "/bundles/products/{product_id}"


[[extensions.targeting]]
module = "./src/ProductVariantDetailsConfigurationExtension.tsx"
# The target used here must match the target used in the module file (./src/ProductVariantDetailsConfigurationExtension.tsx)
target = "admin.product-variant-details.configuration.render"
