# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2025-07"

[[extensions]]
type = "ui_extension"
name = "ext-pos-ui-draft-order-details"

handle = "ext-pos-ui-draft-order-details"
description = "A typescript-react POS UI extension"

# Controls where in POS your extension will be injected,
# and the file that contains your extension’s source code.
[[extensions.targeting]]
module = "./src/Action.tsx"
target = "pos.draft-order-details.action.render"

[[extensions.targeting]]
module = "./src/Block.tsx"
target = "pos.draft-order-details.block.render"

[[extensions.targeting]]
module = "./src/MenuItem.tsx"
target = "pos.draft-order-details.action.menu-item.render"
