api_version = "2025-07"

[[extensions]]
name = "t:name"
handle = "ext-cart-checkout-validation"
type = "function"

description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
