api_version = "unstable"

[[extensions]]
name = "t:name"
handle = "ext-local-pickup-delivery-option-generator"
type = "function"


  [[extensions.targeting]]
  target = "purchase.local-pickup-delivery-option-generator.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"

  [extensions.ui.paths]
  create = "/"
  details = "/"
